{
 "title": "APC UPS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "UpsInstance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery Charge %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apc_charge_percent{instance='$UpsInstance'}",
     "legendFormat": "Battery Charge % ({{job}})"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apc_battery_voltage{instance='$UpsInstance'}",
     "legendFormat": "Battery voltage ({{job}})"
    }
   ]
  },
  {
   "title": "Load %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apc_load_percent{instance='$UpsInstance'}",
     "legendFormat": "Load % ({{job}})"
    }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apc_line_voltage{instance='$UpsInstance'}",
     "legendFormat": "Line Voltage ({{job}})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apc_status{instance='$UpsInstance'}",
     "legendFormat": "Status ({{job}})"
    }
   ]
  },
  {
   "title": "Time available on battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apc_time_left{instance='$UpsInstance'}",
     "legendFormat": "Time available on battery ({{job}})"
    }
   ]
  },
  {
   "title": "Battery Replaced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apc_battery_date{instance='$UpsInstance'} * 1000",
     "legendFormat": "Battery Replaced ({{job}})"
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Battery Charge %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "apc_charge_percent{instance='$UpsInstance'}",
     "legendFormat": "Battery Charge % ({{job}})"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "apc_battery_voltage{instance='$UpsInstance'}",
     "legendFormat": "Battery voltage ({{job}})"
    }
   ]
  },
  {
   "title": "Load %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "apc_load_percent{instance='$UpsInstance'}",
     "legendFormat": "Load % ({{job}})"
    }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "apc_line_voltage{instance='$UpsInstance'}",
     "legendFormat": "Line Voltage ({{job}})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "apc_status{instance='$UpsInstance'}",
     "legendFormat": "Status ({{job}})"
    }
   ]
  },
  {
   "title": "Time available on battery",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "apc_time_left{instance='$UpsInstance'}",
     "legendFormat": "Time available on battery ({{job}})"
    }
   ]
  }
 ]
}